### PR TITLE
do not make nodes which aren't visible to entities and automatically detect minp and maxp if possible

### PR DESCRIPTION
**Pull request by HybridDog**
https://github.com/stujones11/meshnode/pull/3/files?w=1

### CODE REVIEW

**Comment by HybridDog** [comment]
an example: l just removed the connection to the bottom and placed the meshnode block onto it somewhere. lt did automatically find out minp and maxp.
screenshot_20150605_223614

**Comment by stujones11** [comment]
There are some good ideas in this I would like to try and implement but I think there are a few problems to sort out first. The fencelike support appears to be broken and it does not seem to take into account transparent nodes, like glass.

Please note that I have been working on a better implementation which should persist after unload, restart or even a /clearobjects

checkout the 'persistent' branch if you are interested in testing.

**Comment by HybridDog** [comment]
ls it possible to load mesh files after the game was initialized?

**Comment by stujones11** [comment]
I guess it could be wrapped in a 'minetest.after' block and loaded after an arbitrary time. I am not aware of any callback that notifies when the client is fully initialized. The question is, why would you want to do that?

Or do you mean load models on demand, from say a chat command or some other trigger like punching a node or a craft result?

**Comment by HybridDog** [comment]
l mean on demand. Sounds can also be loaded on demand (http://wiki.minetest.net/Sound_Packs).
lf that was possible, a meshnode could be made of one object using mesh instead of many objects.

**Comment by stujones11** [comment]
Yeah, I think something like that would require engine changes. I think there are still plans to add proper voxel area entity (VAE) support at some stage so I really don't want to spend too much effort on this, It's never gonna be perfect. I will, however, continue to add small improvements where I can.

**Comment by HybridDog** [comment]
ok, if VAEs were added, l would need to stop calling VanessaE VaE

**Pull request closed without merging**
